# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!main" # excludes master
      - "!master" # excludes master
      - "!release/production" # excludes master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  cache-warmer:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        id: setup
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        if: ${{ steps.setup.outputs.cache-hit != 'true' }}
        run: pnpm install --frozen-lockfile

  # This workflow contains a single job called "build"
  # test:
  #   # The type of runner that the job will run on
  #   runs-on: ubuntu-latest
  #   timeout-minutes: 10
  #   needs: cache-warmer
  #   strategy:
  #     matrix:
  #       node-version: [ 16.x, 18.x, 20.x ]
  #   env:
  #     ACTIONS_ALLOW_UNSECURE_COMMANDS: true

  #   # Steps represent a sequence of tasks that will be executed as part of the job
  #   steps:
  #     # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
  #     - uses: actions/checkout@v3

  #     - uses: pnpm/action-setup@v2

  #     - name: Setup Node.js environment
  #       uses: actions/setup-node@v3
  #       id: setup
  #       with:
  #         cache: pnpm
  #         node-

  #     - name: Install deps
  #       id: install
  #       run: pnpm install --frozen-lockfile

  #     - name: Test
  #       run: pnpm test-only

  typecheck:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache-warmer
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        id: setup
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm typecheck

  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: cache-warmer
    strategy:
      matrix:
        node-version: [ 16.x, 18.x, 20.x ]
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        id: setup
        with:
          cache: pnpm
          node-version: ${{ matrix.node-version }}

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint-only
