# This is a basic workflow to help you get started with Actions

name: Caprover Delete App

on:
  workflow_call: 
    secrets:
      caproverPassword:
        required: true
        description: Caprover password
    inputs:
      caproverAppName:
        required: true
        type: string
      caproverDomain:
        required: true
        type: string
      envFile:
        required: false
        type: string
      caproverImageName:
        required: false
        type: string
        default: "ghcr.io/${{ github.repository }}:${{ github.sha }}"

jobs:
  cleanup:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - uses: cardinalby/export-env-action@v2
        if: ${{ inputs.envFile }}
        with:
          envFile: ${{ inputs.envFile }}

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - name: Delete Caprover App 🗑️
        run: bunx caprover api --path=/user/apps/appDefinitions/delete --method=POST --data='{"appName":"${{ inputs.caproverAppName }}"}' || true
        env:
          CAPROVER_URL: https://captain.${{ inputs.caproverDomain }}
          CAPROVER_PASSWORD: ${{ secrets.caproverPassword }}
          CAPROVER_IMAGE_NAME: ${{ inputs.caproverImageName }}
          CAPROVER_APP: ${{ inputs.caproverAppName }}
