# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_call:
    inputs:
      bun-version:
        description: 'Bun Version'
        required: false
        default: 'latest'
        type: string
      os:
        description: 'Operating System'
        required: false
        default: 'ubuntu-latest'
        type: string
      mongo-version:
        description: 'MongoDB Version'
        required: false
        default: '7.0.4'
        type: string
  workflow_dispatch:
    inputs:
      bun-version:
        description: 'Bun Version'
        required: false
        default: 'latest'
        type: string
      os:
        description: 'Operating System'
        required: false
        options:
          - 'ubuntu-latest'
          - 'macos-latest'
          - 'windows-latest'
        default: 'ubuntu-latest'
        type: choice
      mongo-version:
        description: 'MongoDB Version'
        required: false
        default: '7.0.4'
        type: string
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch
      - "!main" # excludes the master branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    timeout-minutes: 10
    env:
      MONGOMS_PREFER_GLOBAL_PATH: true
      MONGOMS_VERSION: ${{ inputs.mongo-version || '7.0.4' }}
      BUN_VERSION: ${{ inputs.bun-version || 'latest' }}
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-mongodb-binaries
        name: Cache MongoDB binaries
        with:
          key: ${{ runner.os }}-mongodb-${{ inputs.bun-version }}-${{ env.MONGOMS_VERSION }}
          path: ~/.cache/mongodb-binaries

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun install --concurrent-scripts 1

      - name: Test
        run: bun run test-recursive
        env:
          PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.TEST_PUBLIC_KEY }}

  test-supabase:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      MONGOMS_PREFER_GLOBAL_PATH: true
      MONGOMS_VERSION: ${{ inputs.mongo-version || '7.0.4' }}
      BUN_VERSION: ${{ inputs.bun-version || 'latest' }}
    timeout-minutes: 10
    # disable for now - since it for some reason fails on CI
    if: false 
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-mongodb-binaries
        name: Cache MongoDB binaries
        with:
          key: ${{ runner.os }}-mongodb-${{ inputs.bun-version }}-${{ env.MONGOMS_VERSION }}
          path: ~/.cache/mongodb-binaries

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun install --concurrent-scripts 1

      - uses: supabase/setup-cli@v1
      
      - run: supabase start
        working-directory: ./packages/supabase/supabase-app

      - name: Test
        run: bun run codegen && bun test
        working-directory: ./packages/supabase

  typecheck:
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    timeout-minutes: 10
    env:
      MONGOMS_DISABLE_POSTINSTALL: true
      BUN_VERSION: ${{ inputs.bun-version || 'latest' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun install --concurrent-scripts 1 --ignore-scripts

      - name: Typecheck
        run: bun run typecheck

  lint:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    timeout-minutes: 10
    env:
      MONGOMS_DISABLE_POSTINSTALL: true
      BUN_VERSION: ${{ inputs.bun-version || 'latest' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun install --concurrent-scripts 1 --ignore-scripts

      - name: Lint
        run: bun run lint

  codegen:
    # The type of runner that the job will run on
    runs-on: ${{ inputs.os || 'ubuntu-latest' }}
    timeout-minutes: 10
    env:
      MONGOMS_DISABLE_POSTINSTALL: true
      BUN_VERSION: ${{ inputs.bun-version || 'latest' }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ env.BUN_VERSION }}

      - run: bun install --concurrent-scripts 1 --ignore-scripts

      - run: bun run graphql-codegen
