# This is a basic workflow to help you get started with Actions

name: Test

on:
  workflow_call:
    inputs:
      run-matrix:
        description: 'Run matrix tests'
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
      run-matrix:
        description: 'Run matrix tests'
        required: false
        default: false
        type: boolean
  push:
    branches:
      - "*" # matches every branch that doesn't contain a '/'
      - "*/*" # matches every branch containing a single '/'
      - "**" # matches every branch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        mongo-version: [7.0.4]
        bun-version: ${{ inputs.run-matrix == true && ['1.0.20', '1.0.19'] || ['1.0.20'] }}
        os: ${{ inputs.run-matrix == true && ['ubuntu-latest', 'macos-latest'] || ['ubuntu-latest'] }}  # os: [ubuntu-latest, windows-latest, macos-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      MONGOMS_PREFER_GLOBAL_PATH: true
      MONGOMS_VERSION: ${{ matrix.mongo-version }}
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-mongodb-binaries
        name: Cache MongoDB binaries
        with:
          key: ${{ matrix.os }}-mongodb-${{ matrix.bun-version }}-${{ env.MONGOMS_VERSION }}
          path: ~/.cache/mongodb-binaries

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - run: bun install --concurrent-scripts 1

      - name: Test
        run: bun run test-recursive
        env:
          PRIVATE_KEY: ${{ secrets.TEST_PRIVATE_KEY }}
          PUBLIC_KEY: ${{ secrets.TEST_PUBLIC_KEY }}

  test-supabase:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        mongo-version: [7.0.4]
        bun-version: ${{ inputs.run-matrix == true && ['1.0.20', '1.0.19'] || ['1.0.20'] }}
        os: ${{ inputs.run-matrix == true && ['ubuntu-latest', 'macos-latest'] || ['ubuntu-latest'] }}  # os: [ubuntu-latest, windows-latest, macos-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      PROJECT_ID: ${{ secrets.SUPABASE_PROJECT_ID }}
      MONGOMS_PREFER_GLOBAL_PATH: true
      MONGOMS_VERSION: ${{ matrix.mongo-version }}
    timeout-minutes: 10
    # disable for now - since it for some reason fails on CI
    if: false 
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        id: cache-mongodb-binaries
        name: Cache MongoDB binaries
        with:
          key: ${{ matrix.os }}-mongodb-${{ matrix.bun-version }}-${{ env.MONGOMS_VERSION }}
          path: ~/.cache/mongodb-binaries

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - run: bun install --concurrent-scripts 1

      - uses: supabase/setup-cli@v1
      
      - run: supabase start
        working-directory: ./packages/supabase/supabase-app

      - name: Test
        run: bun run codegen && bun test
        working-directory: ./packages/supabase

  typecheck:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        bun-version: ${{ inputs.run-matrix == true && ['1.0.20', '1.0.19'] || ['1.0.20'] }}
        os: ${{ inputs.run-matrix == true && ['ubuntu-latest', 'macos-latest'] || ['ubuntu-latest'] }}  # os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      MONGOMS_DISABLE_POSTINSTALL: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - run: bun install --concurrent-scripts 1 --ignore-scripts

      - name: Typecheck
        run: bun run typecheck

  lint:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        bun-version: ${{ inputs.run-matrix == true && ['1.0.20', '1.0.19'] || ['1.0.20'] }}
        os: ${{ inputs.run-matrix == true && ['ubuntu-latest', 'macos-latest'] || ['ubuntu-latest'] }}  # os: [ubuntu-latest, windows-latest, macos-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      MONGOMS_DISABLE_POSTINSTALL: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        id: checkout

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - run: bun install --concurrent-scripts 1 --ignore-scripts

      - name: Lint
        run: bun run lint

  codegen:
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        bun-version: ${{ inputs.run-matrix == true && ['1.0.20', '1.0.19'] || ['1.0.20'] }}
        os: ${{ inputs.run-matrix == true && ['ubuntu-latest', 'macos-latest'] || ['ubuntu-latest'] }}  # os: [ubuntu-latest, windows-latest, macos-latest]
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    env:
      MONGOMS_DISABLE_POSTINSTALL: true

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: ${{ matrix.bun-version }}

      - run: bun install --concurrent-scripts 1 --ignore-scripts

      - run: bun run graphql-codegen
